version: 2
tags: ["documentation"]
accept_configuration:
  condition: and
  conditions:
    - condition: property
      property: host.arch
      not_equals_value: AARCH64
    - condition: property
      property: features
      not_contains_value: Disable
    - condition: property
      property: features
      not_contains_value: DebianPackaging
    - condition: property
      property: target.osVersion
      not_equals_value: WebAssembly
    - condition: property
      property: target.osVersion
      not_contains_value: SLES_15

instructions:
  Build:
  - type: EnvironmentVariable
    variableName: BUILD_DOCUMENTATION
    variableValue: "1"
  - type: Group
    instructions:
      - !include "{{qt/qtbase}}/coin_module_build_template_v2.yaml"

  Test:
    - !include "{{qt/qtbase}}/coin_module_test_template_v3.yaml"
    - !include "{{qt/qtbase}}/coin_module_test_docs.yaml"
